services:
  - type: web
    name: trade-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --preload
    envVars:
      - key: DB_HOST
        value: mysql6.sqlpub.com
      - key: DB_PORT
        value: "3311"
      - key: DB_USER
        value: jqlhlxh
      - key: DB_PASS
        value: jTWmxC7fhD44LLzi
      - key: DB_NAME
        value: jqlh_mysql_01
